language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - "python setup.py install"
script:
  - nosetests
notifications:
  emails:
    - yukino0131@me.com
  on_success: always
  on_failure: always
